name: Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *"   # daily
  workflow_dispatch:       # manual run button

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: vn7n24fzkq/github-profile-summary-cards@release/4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
